services:
  - type: web
    name: reafirechat-backend
    runtime: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn -w 2 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker main:app"
    envVars:
      - key: DATABASE_URL
        scope: backend
        fromDatabase:
          name: reafirechat-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: "https://reactfirechat-fe.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11"

  - type: web
    name: reafirechat-frontend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: REACT_APP_API_BASE
        value: "https://reactfirechat.onrender.com"

databases:
  - name: reafirechat-db
    databaseName: reafirechat
    user: reafirechat
    plan: free
